[package]
name = "granite-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "granite"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
clap.workspace = true
cliclack.workspace = true
ratatui.workspace = true
crossterm.workspace = true
futures-util.workspace = true
async-trait.workspace = true
tui-markdown.workspace = true
ratatui-core.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

granite_core = { package = "granite-core", path = "../core" }
provider.workspace = true
tools.workspace = true
